# Generated by Django 2.1.3 on 2019-09-20 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('nickname', models.TextField(blank=True, help_text='昵称', max_length=100, null=True, verbose_name='昵称')),
                ('born_date', models.DateField(blank=True, help_text='出生日期', null=True, verbose_name='出生日期')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], default='M', help_text='性别', max_length=1, verbose_name='性别')),
                ('motto', models.TextField(blank=True, help_text='座右铭', max_length=1024, null=True, verbose_name='座右铭')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
